# Generated by Django 4.2.7 on 2023-11-27 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0002_alter_history_time_stamp_alter_history_view_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Vid_Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('bookmarked', models.BooleanField(default=False)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('disliked', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
